name: node-red

on:
  push:
    paths:
      - '.github/workflows/node-red.yaml'
      - 'apps/node-red/**'
      - '!apps/node-red/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          BASE_DIR=apps/node-red
          VERSION=$(cat ${BASE_DIR}/.version)
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=base_dir::${BASE_DIR}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.prep.outputs.base_dir }}/
          load: true
          tags: |
            mthorley/node-red:${{ github.sha }}

      - name: Vuln scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mthorley/node-red:${{ github.sha }}'
          format: 'table'
#          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.prep.outputs.base_dir }}/
          push: true
          tags: |
            mthorley/node-red:${{ github.sha }}
            mthorley/node-red:${{ steps.prep.outputs.version }}
